### ISSUE TITLE
Cannot regenerate ICY data packages

### ISSUE THREAD

**Issue by simleo** [CellMigStandOrg/biotracks#12]
I have encountered an error while trying to regenerate data packages from the ICY examples:

```
% python3 dpkg.py track_processor_ICY_clean.csv  
Configuration file found: cell_track_dpkg.ini
[...]
>>> opening file: track_processor_ICY_clean.csv
>>> header of the file:
trackID,t,x,y,z

>>> rest of the file:
0.0,0.0,129.8153846153846,995.0153846153846,0.0
[...]

Traceback (most recent call last):
  File "dpkg.py", line 38, in <module>
    dict_ = readfile.read_file(f, track_dict)
  File "/Users/simleo/git/cell_track_dpkg/dpkg/readfile.py", line 368, in read_file
    (objects, links) = read_cellprofiler(f, track_dict)
  File "/Users/simleo/git/cell_track_dpkg/dpkg/readfile.py", line 254, in read_cellprofiler
    digits = x.split('_')[2]
IndexError: list index out of range
```

**Comment by simleo** [comment]
After merging #19, ICY examples work, but not if run directly on the `_clean` files, i.e., we have to run `python3 create_dpkg.py track_processor_ICY.csv`. See https://github.com/CellMigStandOrg/biotracks/pull/19#issuecomment-299463830

**Comment by pcmasuzzo** [comment]
I see the point, but actually ICY does not generate `csv` files at all. You should instead run:
`python3 create_dpkg.py track_processor_ICY.xls` (is the `xls` that is used as a raw file input, as explained [here](https://github.com/CellMigStandOrg/biotracks/tree/master/examples/ICY)).
Having said that, we most likely need to implement #16 to avoid extra issues.

**Comment by simleo** [comment]
> You should instead run: `python3 create_dpkg.py track_processor_ICY.xls`

Forgot to mention that I've done that and it also works.

> it is the `xls` that is used as a raw file input

Apologies for misreading your docs :) This is actually good, because for now we have a 1 to 1 relationship between extensions and formats.

**Comment by pcmasuzzo** [comment]
No problem at all.
And yes, right now we have a 1:1 relationship between extensions and formats 👍
