### ISSUE TITLE
Naming and distribution

### ISSUE THREAD

**Issue by sbesson** [CellMigStandOrg/biotracks#13]
Following the release of 0.1.0, two thoughts with regard the future steps of this library:

- [Packaging and Distributing](https://packaging.python.org/distributing/): should we consider upload the package to [Pypi](http://pypi.python.org/) as this would simplify the distribution/installation by consumers
- Naming: the current name can be seen as slightly cryptic and does not completely reflect the purpose of the library. In the case, we start publishing to Pypi, it might be good to pick up a good starting choice.

At a  high-level, I would summarize it as "a library to convert tracks into a standard format". The `cell` (migration) aspect is related to CMSO and the `dpkg` is specific to the chosen implementation. However, the library could be used for tracks applied to non-cell migration experiments and could also be used to write into other standard formats (CMSO or not). My best proposal at this point would be `pip install tracks_converter`. Opening this as an issue to channel the discussion.

**Comment by pcmasuzzo** [comment]
OK for packaging and distributing - this will require some work, I suspect, and I can definitely use some help :)

As for the naming, agreed on current cryptic nature. `tracks_converter` sounds good to me. Any other suggestions more than welcome. @gsergeant?

**Comment by simleo** [comment]
Could we add something to the name to suggest the biological domain, e.g., `biotracks_converter`? Or even `biotracks_formats` :)

Or simply `biotracks`. Easier to memorize.

**Comment by simleo** [comment]
Re: distribution, I think there's some more work to be done before we can upload to PyPI. Perhaps we can keep this release only on GitHub.

**Comment by pcmasuzzo** [comment]
I like `biotracks` 👍 

But perhaps `biotracks_converter` better for the library, and `biotracks` for the format? (oooops. Feel free to shut me at any time).

**Comment by gsergeant** [comment]
I like `biotracks` better as well for naming. More concise and the 'bio' prefix works well (cause I'm not sure how our objects-links infrastructure could be used in a non-bio setting). I'm not sure if we would split the naming up between the spec and library, I say it depends whether people will find it confusing or not.

The Pypi distribution seems really interesting though! 😃 Will def look more into that.

**Comment by pcmasuzzo** [comment]
I think `biotracks `is something we all (here) agree upon, unless @sbesson says no.

Question that remains: two names for format + converter, or one name?

**Comment by simleo** [comment]
I would call the Python package `biotracks`, not `biotracks_converter`. The latter is longer and has an underscore, both of which are [discouraged in PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names).

**Comment by sbesson** [comment]
Closed via #17 and https://pypi.python.org/pypi/biotracks
