### ISSUE TITLE
Role of config file in data package creation

### ISSUE THREAD

**Issue by simleo** [CellMigStandOrg/biotracks#14]
Looking at the [current status](https://github.com/CellMigStandOrg/cell_track_dpkg/tree/d5917476c92ed4e0dc08b33b8783abbf18f1c641) of both the code and the examples, it is not clear what configuration parameters from the `.ini` file are meant for.

Is the configuration file specifying where to look for a specific column name in the *source* file (the one produced by the tracking software), or is it specifying how the column should be called in the *target* `.csv` file?

Out of our [current readers](https://github.com/CellMigStandOrg/cell_track_dpkg/blob/d5917476c92ed4e0dc08b33b8783abbf18f1c641/dpkg/readfile.py), only the CellProfiler one takes a configuration object as an extra parameter. However, the reader is using the config in a mixed way:

* In the case of the X and Y coordinates, the reader uses the config to find the corresponding columns

* In the case of the object and link IDs, the reader uses (actually **should** use, because they are hardwired in the current version, see [line 309](https://github.com/CellMigStandOrg/cell_track_dpkg/blob/d5917476c92ed4e0dc08b33b8783abbf18f1c641/dpkg/readfile.py#L309) for instance) the config to name the output columns

* The frame ID specified in the example config (`ImageNumber`) is used both as an input and an output parameter (and is also hardwired rather than read from the config)

Other name patterns are assumed to be fixed and known in advance (e.g., `"TrackObjects_Label_*"`). In particular, the examples specify `object_id_cmso = ObjectID` but the input column name is `ObjectNumber`, which is, again, hardwired in the reader. Are these names really fixed in CellProfiler, or in the blob detection module, or in `ExportToSpreadsheet`? Or do they depend on the pipeline config file (from the examples we have it looks like the answer to this is no)?

In the TrackMate and Icy readers, the source structure is fixed and known in advance, so one would assume that config items are only meant for the output csv files. However, the current readers do not take a config item as an extra argument, so everything is hardwired to the same values set in the `.ini` file in the current examples.

In https://github.com/CellMigStandOrg/cell_track_dpkg/issues/8 I proposed adding a level of indirection for column names by placing our own ID in the `"name"` field and the original ID in `"title"`. However, in the current workflow we actually never preserve the original file from the tracker (that would only make sense for a CSV anyway), but rather write our own `.csv` files together with the JSON. If we intend to do this for all formats, we might as well always use the same column names, which we can define in a single place somewhere in our code. 

Due to the above, my proposal would be to use configuration files only to let the user specify any variable info in the source format, and always use our own names for the output datapackage. Note that this is somewath orthogonal to the indirection problem, since in that case we would still use our predefined, configuration-independent names in the `.json` as pointers to the real ones in the `.csv`.

**Comment by simleo** [comment]
See also PR #15

**Comment by pcmasuzzo** [comment]
In the ideal case, the configuration file (`ini`) should _only_ specify where to look for a specific column name in the _source_ file (the one produced by the tracking software), and _should not_ specify how the columns are called in the _target_ file (even though this is the case).

For the specific `CellProfiler `case, some name patterns are indeed to be known in advance and they _do not_ change across pipelines (e.g. "`TrackObjects_Label_*`").
I agree with you that the current strategy is not optimal, and I also agree with the proposal to use configuration files only to let the user specify any variable info in the source format, and use our own names for the `output datapackage`.

Looking into PR #15 now.

**Comment by simleo** [comment]
Fixed in #41. To recap:

* The configuration file is now optional, except for specific formats where one or more input fields are not known in advance. In the latter case, the `TRACKING_DATA` section has to provide the missing info by mapping standard CMSO field names to the actual ones. In any event, the `TRACKING_DATA` section serves only as an aid for interpreting the **input**, while output field names are always the standard ones.
* The `TOP_LEVEL_INFO` section carries information that will be transferred directly to the JSON data package's descriptor top-level (so it only controls the **output**). The data package specs require the `name` field to be present, but we fall back to a default if it's not specified in the configuration, so this section is always optional.
