### ISSUE TITLE
Spec compliance

### ISSUE THREAD

**Issue by simleo** [CellMigStandOrg/biotracks#3]
In our data package examples we should ensure compliance with the specs at https://specs.frictionlessdata.io/data-package. For instance, `"name": "objectsTable"` is not valid because "name" cannot contain uppercase characters, so the value might be changed to "objects_table". Validity can be checked with:

```python
import datapackage
datapackage.DataPackage("datapackage.json").validate()
```

And here's the error for the above case:

```
ValidationError: u'objectsTable' does not match u'^([a-z0-9._-])+$'

Failed validating u'pattern' in schema[u'properties'][u'resources'][u'items'][u'properties'][u'name']:
    {u'description': u"An identifier for this package. Lower case characters with '.', '_' and '-' are allowed.",
     u'pattern': u'^([a-z0-9._-])+$',
     u'title': u'Name',
     u'type': u'string'}

On instance[u'resources'][0][u'name']:
    u'objectsTable'
```

Ensuring that generated data packages will be compliant is trickier, because we'd need to perform the same checks that `datapackage` does on configuration files etc. Rather, it should be the user's responsibility to check that any setting that will end up in a restricted data package field is compliant with the corresponding specs.

**Comment by danfowler** [comment]
@simleo there's an open discussion on this: https://github.com/frictionlessdata/specs/issues/463

**Comment by simleo** [comment]
@danfowler thanks! Another thing I'm wondering about is whether there is a way to know which version of the specs a given version of the Python API is implementing (and if older specs are still available).

**Comment by danfowler** [comment]
@simleo thanks for raising the issue: https://github.com/frictionlessdata/datapackage-py/issues/149

@roll is the best one to answer this
