### ISSUE TITLE
Add MOSAIC reader

### ISSUE THREAD

**Issue by pcmasuzzo** [CellMigStandOrg/biotracks#36]
Add a reader for cell track files generated through the [MOSAIC Fiji/ImageJ particle tracker plugin ](http://mosaic.mpi-cbg.de/?q=downloads/imageJ)(based on algorithm of [Sbalzarini and Koumoutsakos, 2005](http://mosaic.mpi-cbg.de/docs/Sbalzarini2005a.pdf)).

**Comment by agbeltran** [comment]
This was resolved in #54 - closing the issue now.
