### ISSUE TITLE
CellProfilerReader: wrong indentation

### ISSUE THREAD

**Issue by simleo** [CellMigStandOrg/biotracks#40]
In `CellProfiler.read_objects`, [the objects data frame is updated at every iteration](https://github.com/CellMigStandOrg/biotracks/blob/3b5e0b2fca271a7cfd36777976641a415d0a508a/biotracks/readfile.py#L230) due to a wrong indentation. This is not a source of errors because after the loop `objects_df` has the last value, which is the correct one, but it's an obvious waste of resources.

**Comment by agbeltran** [comment]
This was resolved in #54, closing the issue now.
