### ISSUE TITLE
cmso_link_id starts from 1 for CellMIA only

### ISSUE THREAD

**Issue by gsergeant** [CellMigStandOrg/biotracks#50]
Just noticed this and checked examples of all tracking software folders.
The cmso_link_id in the links.csv all starts from 0 except in the [CellMIA example](https://github.com/CellMigStandOrg/biotracks/blob/master/examples/CELLMIA/example_1/dp/links.csv), where it starts from 1.

Probably requires just a tiny number change. I'll see if I can find the specific script file and line nr.

**Comment by simleo** [comment]
While the specs do not state that link IDs have to be 0-based (or even consecutive!) it's better to be consistent and tidy (i.e., I agree on fixing this).

**Comment by gsergeant** [comment]
This issue results from CellMIA's tracking: `cmso_link_id` is inferred straight from the software's tracking file. ([readfile.py](https://github.com/CellMigStandOrg/biotracks/blob/master/biotracks/readfile.py#L382) --  [CellMIA output](https://github.com/CellMigStandOrg/biotracks/blob/master/examples/CELLMIA/example_1/0001_mode1_z000_f000_tracking.txt))

A df.replace() will probably do the job. Will apply and open PR.
